spring:
  config:
    import: optional:file:./app.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  storage:
    local-root: ${STORAGE_LOCAL_ROOT:./data/uploads}

  qdrant:
    host: ${QDRANT_HOST:localhost}
    port: ${QDRANT_PORT:6334}
    use-tls: ${QDRANT_USE_TLS:false}
    collection-name: ${QDRANT_COLLECTION_NAME:chunks}

  embedding:
    base-url: ${EMBEDDING_BASE_URL:http://localhost:11434}
    model: ${EMBEDDING_MODEL:qwen3-embedding:0.6b}
    dimensions: ${EMBEDDING_DIMENSIONS:1024}

server:
  port: 8080