package org.ai_processor.processing.embeddings

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(EmbeddingProperties::class)
class EmbeddingConfiguration